version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
